version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: fallen-todo_server_1
      APP_PORT: 5001

  server:
    image: carlosfallen/todo:latest
    restart: on-failure
    init: true
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
