version: "3.7"

services:
  app:
    image: carlosfallen/todo:2.1.1
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - umbrel_main_network
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - PORT=3001
    
networks:
  umbrel_main_network:
    external: true
