version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: fallen-todo_server_1
      APP_PORT: 5173

  server:
    image: carlosfallen/todo:latest
    restart: on-failure
    init: true
    environment:
      - NODE_ENV=production
    ports:
      - "5173:5173"
      - "3001:3001"
    volumes:
      - ${APP_DATA_DIR}:/app/data
      - ${UMBREL_ROOT}/data/storage:/storage
