version: '3.8'
services:
  samba:
    image: carlosfallen/samba:latest
    container_name: samba
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/local:/shares/local:rw
      - ${APP_DATA_DIR}/data/Win11:/shares/Win11:ro
      - ${APP_DATA_DIR}/config/smb.conf:/etc/samba/smb.conf:ro
    environment:
      - SAMBA_PASS=jorge
    security_opt:
      - no-new-privileges:true
