version: "3.8"

services:
  app:
    image: carlosfallen/apk-store:latest 
    restart: on-failure
    ports:
      - "${APP_PORT}:5174"
    volumes:
      - ${APP_DATA_DIR}/apks:/app/public/apks
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5174
