[global]
   workgroup = WORKGROUP
   security = user
   map to guest = Bad User

[Local]
   comment         = Compartilhamento “local” para Jorge
   path            = /shares/local
   browsable       = yes
   guest ok        = no
   valid users     = jorge
   read only       = no
   create mask     = 0775
   directory mask  = 2775

[Win11]
   comment           = Compartilhamento “Win11” somente leitura
   path              = /shares/Win11
   browsable         = yes
   guest ok          = no
   valid users       = jorge
   read only         = yes
   delete readonly   = no
