version: '3.7'

services:
  hbbs:
    container_name: fallen-rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.14
    command: hbbs
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - ./data/hbbs:/root
    restart: on-failure

  web:
    container_name: fallen-rustdesk-web
    image: nginx:1.27-alpine
    volumes:
      - ./data/www:/usr/share/nginx/html:ro
    ports:
      - "5177:80"
    restart: on-failure
