version: "3.8"

services:
  app:
    image: carlosfallen/superips:latest
    restart: unless-stopped
    network_mode: "host"          # usa a rede do host
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ./dist:/app/dist          # frontend buildado
      - ./backend:/app/backend    # backend + configs
    environment:
      - NODE_ENV=production
      - DB_HOST=127.0.0.1        # host do Umbrel
      - DB_PORT=5432
      - DB_USER=superips_user
      - DB_PASSWORD=359628
      - DB_NAME=superips_db
      - JWT_SECRET=TI
      - JWT_REFRESH_SECRET=TI_REFRESH
    command: sh -c "/app/wait-for-postgres.sh $DB_HOST $DB_PORT bun backend/dist/index.js"
