version: "3.7"

services:
  kavita:
    image: jvmilazz0/kavita:nightly-0.8.7.8
    container_name: kavita
    ports:
      - "5000:5000"
    volumes:
      - /mnt/data/umbrel/home/Downloads/mangas:/manga
      - /mnt/data/umbrel/home/Downloads/mangas/config:/kavita/config
    environment:
      - TZ=America/Fortaleza
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
